### ISSUE TITLE
Using pre-trained weights from SegFormer confused me

### ISSUE THREAD

**Issue by lilong-wen** [rulixiang/wetr#17]
To my understanding, the SegFormer's weights are trained with fully supervised annotations with class and location informations, directly using those weights as initial parameters dosen't really looks like a real weakly supervised schema.

**Comment by rulixiang** [comment]
Pre-trained weights [here](https://github.com/rulixiang/afa#download-pre-trained-weights) means imagenet-1k pre-trained weights (see [here](https://github.com/NVlabs/SegFormer#training)), NOT pre-trained with full supervision. I have updated README to avoid confusion.

**Comment by lilong-wen** [comment]
Thanks for your reply,  but I still don't get it. The SegFormer pre-trained weights were surely obtained by training under a fully supervised setting using ImageNet-1K. So, the difference lies in the different datasets?  The Weakly supervised in this paper's scenario means weak supervision on COCO and VOC datasets combined with transferred knowledge from ImageNet-1K, is that a correct understanding?
